name: AgiD Public code validation
on: workflow_call
jobs:
  publiccode_validation:
    runs-on: ubuntu-latest
    name: publiccode validation
    steps:
    - uses: actions/checkout@v5
    - uses: italia/publiccode-parser-action@v1.4.3
      with:
        publiccode: 'publiccode.yml' # relative path to your publiccode.yml
        comment-on-pr: true
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
